noop(test infra) rm obsolete dep to fix broken indirect(?) dep to binstall
and then in my own github ci/cid, pasting from
https://github.com/jzacsh/vcsq/actions/runs/12738221283/job/35500226306
run I got this failure:

```
Run cargo install cargo-binstall
    Updating crates.io index
 Downloading crates ...
  Downloaded cargo-binstall v1.10.20
  Installing cargo-binstall v1.10.20
    Updating crates.io index
error: failed to compile `cargo-binstall v1.10.20`, intermediate artifacts can be found at `/tmp/cargo-installBZQ9Sc`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  failed to select a version for the requirement `log = "^0.4.24"`
  candidate versions found which didn't match: 0.4.22, 0.4.21, 0.4.20, ...
  location searched: crates.io index
  required by package `cargo-binstall v1.10.20`
  if you are looking for the prerelease package it needs to be specified explicitly
      log = { version = "0.4.0-rc.1" }
Error: The operation was canceled.
```

probably should figure out why (if really necessary) that my ci/cd's
runtime install is picking up on Cargo.toml of my own codebase... I'd
think they'd be orthogonal.

Or maybe this is related to binstall's own commit 17 hours ago (my error
is from a few minutes ago though but maybe they haven't done a `cargo
publish` and I need that?):
https://github.com/cargo-bins/cargo-binstall/commit/9d375f94612cc3f3abe749bab41b65d5edb7665f